### ISSUE TITLE
support for multiple controllers

### ISSUE THREAD

**Issue by wivaku** [asev/homeassistant-uponor#1]
The plugin is now hardcoded for a single controller. 
In my case I have multiple controllers:
```
"cust_C1_T1_name","Guest Bedroom"
"cust_C1_T2_name","Office"
"cust_C1_T3_name","Bedroom"
"cust_C1_T5_name","Craft Room"
"cust_C2_T1_name","Downstairs"
```

So, at least when there are multiple controllers, naming should be e.g. `climate.climate_cXtY`,
and the get/set actions should take both controller and thermostat as argument.

**Comment by BasTijs** [comment]
I have a setup with 3 controllers and 11 thermostats, where the first controller is the master. I currently only see the thermostats connected to the first controller. How to fix this?

**Comment by wivaku** [comment]
hoi, this requires updated version of the plugin which implements the two items mentioned above: identify thermostat by combination of controller and thermostat ID. Now it is hardcoded to look for + work with only the first controller ("C1_...").

**Comment by BasTijs** [comment]
@wivaku hallo, do you have any example code to fix it?

**Comment by wivaku** [comment]
Not sure I understand. This *is* the repository of the actual [source code](https://github.com/asev/homeassistant-uponor/tree/master/custom_components/uponor). 
In `__init__.py` you will see the controller is hard coded. I am hoping the developer (@asev) or others can take a look.

**Comment by asev** [comment]
I'll implement this over the weekend. I had this idea but was postponing for a while.
Thanks for the feedback.
