### ISSUE TITLE
add as add-on repository

### ISSUE THREAD

**Issue by kng** [asev/homeassistant-uponor#12]
Hi, tried to add via supervisor -> add-on store -> repositories -> manage  add-on repositories.
I guess this is the wrong path, but possible to implement ?

`20-11-12 10:25:11 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/asev/homeassistant-uponor repository`
`20-11-12 10:25:13 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a0bf71ef/repository.json: [Errno 2] No such file or directory: '/data/addons/git/a0bf71ef/repository.json'`
`20-11-12 10:25:14 ERROR (MainThread) [supervisor.store] https://github.com/asev/homeassistant-uponor is not a valid add-on repository. `
`20-11-12 10:25:14 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/asev/homeassistant-uponor`
`20-11-12 10:25:14 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove`

**Comment by asev** [comment]
Hello.
This is custom integration. Not an add-on.
You can add it [via HACS](https://hacs.xyz/docs/faq/custom_repositories).
Also you can copy the custom_components folder to your own Home Assistant /config folder.
And follow Installation steps from README.
