### ISSUE TITLE
This custom supports module X-245?

### ISSUE THREAD

**Issue by marcospg75** [asev/homeassistant-uponor#17]
Hello again,
I wonder if this component supports module Smatrix Base Pulse (X-245).
If only interacts with the app, I suppose that it's independent of the main module, as the connection is done by the R208, right?
Best regards

**Comment by thecem** [comment]
It supports Smatrix Wave Base Pulse via R-208.

**Comment by marcospg75** [comment]
The only difference between Wave and "no Wave" is the support for wireless room thermostates.
All the interaction of your custom_component is with the Uponor API... and all the information is collected with the R208, so I guess, the way as the module contact thermostates is nor relevant.
I will give you feedback when I have it ;)

Thanks in advance

**Comment by marcospg75** [comment]
Hello Again...
I can confirm that this custom component suports also Smatrix Base Pulse X-245 via R208 :), so you can update the documentation and the supported devices

**Comment by asev** [comment]
Thanks @marcospg75 for the update.
