### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by thecem** [asev/homeassistant-uponor#18]
I found a log error after switching the state from off to heating.
So I there is a issue with the reload of previous set temp?

Pls have a look! Thanks a lot...

```
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 20:13:05 (2 occurrences)
Last logged: 20:13:10
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for uponor doing I/O at custom_components/uponor/__init__.py, line 163: self._client.send_data({var: setpoint})
```

**Comment by thecem** [comment]
I double checked the issue, it seems on every heating / off toggle the error will be raised.
HA Version 2021.1.4

@asev: Do you need additional information for this?

Thanks a lot!

**Comment by asev** [comment]
You helped a lot. Thank you.
