### ISSUE TITLE
Example using POST Request to Uponor API

### ISSUE THREAD

**Issue by marcospg75** [asev/homeassistant-uponor#20]
Hello,
Thanks for the new version with graphic UI :) That's great!

I miss some example of using the new service to communicate with Uponor API.
Can you document this service and how to use it?
(perhaps, how to set ECO offset, or cooling offset or any other variable available...)

Best Regards

**Comment by asev** [comment]
Hello.
I could briefly mention few examples. But I'm not planning to document it in README.
To set eco mode offset to 1℃ for single thermostat:
```
service: uponor.set_variable
data:
  var_name: C1_T3_eco_offset
  var_value: 18
```
_Note: Multiple ℃ by 18. So, to set offset to 3℃ var_value would be 54._

To set cooling offset for entire system use var_name `sys_heat_cool_offset`. var_value should be multiplied by 18 as well.

You've already shared your config values. So you can play and try to change some of them. In most cases you'll get warning in logs that this value is read only.
Please be aware that I'm not taking any responsibility if you'll brake anything. :)

Hope you'll find it useful.
