### ISSUE TITLE
Warning in HA logs

### ISSUE THREAD

**Issue by marcospg75** [asev/homeassistant-uponor#21]
Hello,
When HA restarts I can find this message regarding uponor integration:

No 'version' key in the manifest file for custom integration 'uponor'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'uponor'

So... I'm reporting to the maintainer :)

Thanks in advance!!!

**Comment by asev** [comment]
Thanks for the report.
This should be fixed in v0.8.1
