### ISSUE TITLE
Integration not working after update

### ISSUE THREAD

**Issue by arva-zz** [asev/homeassistant-uponor#22]
Hi!

I was away from home from Febryary and this morning did all available in HACS including Uponor integration. After that all entities disappeared. Before update everything was ok

Unfortunately I didn't look what was the version before update, but probably some version from late January/ early February.

Uponor module:  R-208

My configuration.yaml:

<img width="327" alt="Screenshot 2021-04-13 at 11 06 34" src="https://user-images.githubusercontent.com/994627/114518728-54402380-9c48-11eb-9d6a-8b339da0d3f1.png">

If delete the configuration and try the 4th step (Go to Configuration > Integration" > Add Integration > Uponor. Finish the setup.), when entering IP adresss I get error "Invalid hostname or IP address."
<img width="402" alt="Screenshot 2021-04-13 at 11 01 55" src="https://user-images.githubusercontent.com/994627/114518174-bfd5c100-9c47-11eb-9e3f-77f694beac81.png">
However the IP adress is correct and shows the same 403 error as it has been showing:
<img width="1115" alt="Screenshot 2021-04-13 at 11 03 24" src="https://user-images.githubusercontent.com/994627/114518349-f01d5f80-9c47-11eb-908a-dabc6a0c1139.png">

Does the integration have some kind of logging where to troubleshoot or you have some idea what has been changed and could cause the problem?

**Comment by BasTijs** [comment]
I have the same problem, just deleted my old files and replaced them with the new and restarted HA. Then I've tried to add the integration again but I'm also getting invalid IP.

**Comment by martinarva** [comment]
My quess is that it was caused by v0.8.0 update.

**Comment by arva-zz** [comment]
Any news regarding the issue?

**Comment by BasTijs** [comment]
For me it is still broken unfortunatley

**Comment by lillpjot** [comment]
It didn't work for me either, but I patched it according to the pullrequest and then it worked.
So please try the PR.

**Comment by BasTijs** [comment]
Ok great, that seems to work for me

**Comment by javicmsal** [comment]
It is not working in my home assistant. I get invalid hostname or IP address as user arva-zz. Is there any way to solve it? I tried to install version 7.2 (I did not have it installed before) but I get a mistake that says file __init__.py cannot initialize the integration...
I would be so grateful if you can provide any solution. Thanks in advance!

**Comment by thecem** [comment]
Try the PR: change in the files following:
https://github.com/asev/homeassistant-uponor/pull/23/commits/5e31da97c49a1464dd3dea336983fc1a2987e7bb

**Comment by thecem** [comment]
Afterwards pls let us know if the PR is working for you…

**Comment by asev** [comment]
Sorry for such mistake and late reaction.
And thanks to @dunv for the pull request.

**Comment by martinarva** [comment]
> Sorry for such mistake and late reaction.
> 
> And thanks to @dunv for the pull request.

Thanks!

**Comment by javicmsal** [comment]
Now it is working! So thank you so much! I am really happy.Best regards, Javier.

    En viernes, 4 de junio de 2021 16:02:12 CEST, thecem ***@***.***> escribió:  
 
 


Afterwards pls let us know if the PR is working for you…
