### ISSUE TITLE
use eco preset

### ISSUE THREAD

**Issue by wivaku** [asev/homeassistant-uponor#3]
Would it be possible / useful to use the eco mode of the thermostat?
I.e. enable the climate entities feature SUPPORT_PRESET_MODE (16), and use the ECO preset.

Not sure which API setting is to be used, maybe: `mode_comfort_eco`?
(`eco_setting` is a read only parameter)

```
"C2_eco_mode_presence","0"
"C2_eco_mode_forced_pub_thermo","0"
"C2_device_system_alarm_eco_loss","0"
"C2_T1_mode_comfort_eco","0"
"C2_T1_eco_profile_number","0"
"C2_T1_eco_offset","72"
"C2_T1_stat_cb_comfort_eco_mode","0"
"C2_T1_stat_cb_eco_forced","0"
"C2_T1_stat_comfort_eco_mode","0"
"C2_T1_stat_eco_program","0"
"C2_T1_eco_setting","0"
"C2_id_sys_dev_eco","0"
```

**Comment by thecem** [comment]
If the ECO mode is in the Uponor App enabled the following parameter is set to one and the offset will be calculated in the target temp (Fahrenheit) // (offset - 320)*5/9/10.

```
"C2_T1_eco_offset","72"
"C2_T1_stat_cb_comfort_eco_mode","1"
```

I don't find a eco setting to change, but i tried not all. Maybe the following parameter is writable and in combination with the day profile (on/off eco) the setting is usable.
1 is for the "My ECO-Profile 1"
and 
2 is for the "My ECO-Profile 2"

```
C2_T1_Sunday: "000fffffffc0"
cust_C1_T12_Custom_Eco_Profile: "2"
```

**Comment by asev** [comment]
Read-only presets added to the integration. You can activate away preset with `switch.uponor_away` but there is no easy way to activate it for single thermostat.
