### ISSUE TITLE
Unable to see relative humidity as an entity

### ISSUE THREAD

**Issue by ggravem** [asev/homeassistant-uponor#31]
The data from the uponor system contains relative humidity for each thermostat, but I am unable to see that in HA. Would be useful for e.g. ventilation fan automations.

**Comment by thecem** [comment]
![A7ED085E-315C-4F56-B801-FEFEAC358932](https://user-images.githubusercontent.com/46648579/190895081-dc019ee1-5d92-4b20-b68e-f7e77ecef66a.jpeg)

you could directly access the humidity vie the attributes, or generate a template sensor out of the humidity attribute.

**Comment by ggravem** [comment]
Thanks, I understand now!
