### ISSUE TITLE
No option for "Reload" the integration

### ISSUE THREAD

**Issue by marcospg75** [asev/homeassistant-uponor#35]
Hi asev,
I notice that this integration has no option to reload as others.
It's very useful this option to solve some issues that happen during the reboot of HA.
Can you add this option?
Thanks in advance!!!

**Comment by njonkman** [comment]
Please... fix this

**Comment by mediaNen** [comment]
Yes please, this would be nice.

**Comment by dave-code-ruiz** [comment]
Fork that solves most issues in this integration:

https://github.com/asev/homeassistant-uponor/issues/46

**Comment by dave-code-ruiz** [comment]
Fork #53 solves this issue, you can close it
