### ISSUE TITLE
Setting a temperature via HA reverts after short time

### ISSUE THREAD

**Issue by ronderksen** [asev/homeassistant-uponor#36]
I'm not sure this is a solvable issue, but I can't change the target temperature in HA. Whenever I change it, it gets reset to the previous value after a few seconds. I guess the hardware temperature controls that I have in each room overrules the HA setting. Can you confirm that this is the case, or is there something that I need to configure differently?

**Comment by dave-code-ruiz** [comment]
Fork that solves most issues in this integration:

https://github.com/asev/homeassistant-uponor/issues/46
