### ISSUE TITLE
state shown as "heat" when idle?

### ISSUE THREAD

**Issue by wivaku** [asev/homeassistant-uponor#4]
The state is listed as "heat"?
It was [my understanding](https://developers.home-assistant.io/docs/entity_climate/) that this should be "idle".

Could be that this is related to how the thermostat appears in Homekit. There I see: current temperature = e.g. 23 degrees, and **heat to** 7 degrees. 

Would assume: if temp is set to **minimum temperature** then treat the thermostat as **idle**.

![image](https://user-images.githubusercontent.com/2084872/80221174-32b7e780-8645-11ea-84c5-aa8d0254f26f.png)

**Comment by asev** [comment]
State represents which mode is active. You can see list of available options [here](https://developers.home-assistant.io/docs/entity_climate/#hvac-modes).
In our case it can be in **heat** or **off** modes.
_hvac_action_ shows current action. [List of available options](https://developers.home-assistant.io/docs/entity_climate/#hvac-action).
In our case it can be **heating**, **off** or **idle**.
When temperature set to minimum both state and action are **off**.

**Comment by wivaku** [comment]
That is currently not the case. 
For my thermostats all states are “heat”, also for the thermostats set to 7 degrees. 
The “idle” I referred to came from the documentation for `hvac_mode`:

> The current operation (e.g. heat, cool, idle). Used to determine state.

**Comment by asev** [comment]
You're right. This issue has been fixed couple days ago with 98e1bd9.
Please let me know if it still does not work as expected.

**Comment by wivaku** [comment]
Thanks for the update.
I believe HVAC_ACTION should be IDLE when the desired temperature is achieved (instead of OFF).
The device is still on, it is just not performing an action.

**Comment by asev** [comment]
It works as you described.
![image](https://user-images.githubusercontent.com/10020928/80316139-c388f180-8804-11ea-9132-6aa1c7c61d1b.png)
It is off

**Comment by wivaku** [comment]
You are right, never mind! Thanks for checking.
