### ISSUE TITLE
Fork that solves most issues in this integration

### ISSUE THREAD

**Issue by dave-code-ruiz** [asev/homeassistant-uponor#46]
I create a PR that solves most issues in this integration

https://github.com/asev/homeassistant-uponor/pull/45

If @asev can to merge that , this solves most issues in this integration

**Comment by dave-code-ruiz** [comment]
For thanks for collaboration:

<a href="https://www.buymeacoffee.com/davecoderuiz" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" height="41" width="174"></a>

**Comment by arrelid** [comment]
@dave-code-ruiz You didn't run into this by any chance? https://github.com/asev/homeassistant-uponor/issues/47
