### ISSUE TITLE
TypeError: UponorStateProxy.async_update() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by kikediazfernandez** [asev/homeassistant-uponor#50]
After updating to 0.9.1, I'm getting every 30 seconds this error:

`ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _TrackTimeInterval._interval_listener(<Job track ti... of ...>>)>)>>) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1603, in _interval_listener
    self.hass.async_run_hass_job(self._run_job, dt_util.utcnow(), background=True)
  File "/usr/src/homeassistant/homeassistant/core.py", line 939, in async_run_hass_job
    return self._async_add_hass_job(hassjob, *args, background=background)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 749, in _async_add_hass_job
    hassjob.target(*args), name=hassjob.name, loop=self.loop
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: UponorStateProxy.async_update() takes 1 positional argument but 2 were given`

Removing event_time from that function maybe was't a good idea. From the async_track_time_interval implementation:
"""Add a listener that fires repetitively at every timedelta interval.
    **The listener is passed the time it fires in UTC time**.
    """

**Comment by arrelid** [comment]
+1, getting the same error on 0.9.1

**Comment by dave-code-ruiz** [comment]
For thanks for collaboration:

<a href="https://www.buymeacoffee.com/davecoderuiz" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" height="41" width="174"></a>
