### ISSUE TITLE
filter out bogus data

### ISSUE THREAD

**Issue by wivaku** [asev/homeassistant-uponor#6]
Sometimes HA shows bogus data from multiple thermostats.
I have 4 thermostats on one controller, all of them sometimes (once a week?) show a peak of ±2000 degrees:

![image](https://user-images.githubusercontent.com/2084872/81942192-1e3e8d80-95fa-11ea-8fe1-6e3689add8cd.png)

Interestingly enough, this happens for all 4 at the same time, and it does not happen for the other controller.

This throws off the graphs. 
Is there a way to filter out bogus data (any temp > max temp of thermostat e.g. 35 degrees)?

**Comment by asev** [comment]
Thanks for reporting the issue. I've noticed the same and it happens ~2 times a month.
