### ISSUE TITLE
If thermostat is off and HA reboots temp is set afterwards to 20 degree Celius. 

### ISSUE THREAD

**Issue by thecem** [asev/homeassistant-uponor#7]
I use window sensors to switch off the thermostat. If I reboot HA in between the temperature is set to 20 degree Celsius, regardless what is was prior.
That is relay good to save energy, but my wife is killing me...

Is there a possibility to save the temp status during the HA reboot? Or to set it to a default value for every room.

Thanks a lot for this good integration!

**Comment by asev** [comment]
Hello @thecem. Thanks for the feedback.
I hope this issue wasn't relevant during the summer and your wife haven't killed you. :)

If it does not work, try to restart home assistant.

**Comment by thecem** [comment]
Hi Asev, thanks a lot! Tested and it work‘s.
So wife is happy, but the energy savings after rebooting and forgetting to reset the temp is gone.... ;-)
Even better, than being killed by wife....🤣
